# Generated by Django 5.2.14 on 2026-05-18 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Desktop Publishing/Application Support', 'Desktop Publishing/Application Support'), ('Coaching Supprot/Set-up Assistance/ Trainings', 'Coaching Supprot/Set-up Assistance/ Trainings'), ('Internal & Web-based System Concerns', 'Internal & Web-based System Concerns'), ('Website Access Request', 'Website Access Request'), ('Others (Pls. Specify)', 'Others (Pls Specify)')], max_length=100)),
                ('sub_category', models.CharField(choices=[('Graphics Layout/Photo Editing', 'Graphics Layout/Photo Editing'), ('MS Word / Excel / Powerpoint / Visio Formatting', 'MS Word / Excel / Powerpoint / Visio Formatting'), ('IT Devices / Hardware', 'IT Devices / Hardware'), ('Software Applications', 'Software Applications'), ('Equipment / Devices', 'Equipment / Devices'), ('Technical Services', 'Technical Services'), ('Data Correction / Amendments', 'Data Correction / Amendments'), ('Opascor Terminal Operating System (OpTOS)', 'Opascor Terminal Operating System (OpTOS)'), ('OpTOS Blockcontrol', 'OpTOS Blockcontrol'), ('OpTOS Reefer', 'OpTOS Reefer'), ('OpTOS Analytics', 'OpTOS Analytics'), ('OpTOS Weighing', 'OpTOS Weighing'), ('Internet Access Schedule', 'Internet Access Schedule'), ('Others - Please Specify', 'Others - Please Specify')], max_length=200)),
                ('description', models.TextField()),
                ('others_specify', models.CharField(blank=True, max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('assigned_to', models.CharField(blank=True, max_length=100)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Admin', 'Admin'), ('Finance', 'Finance'), ('MIS', 'MIS'), ('Operational/General Management', 'Operational/General Management'), ('Human Resources', 'Human Resourcres'), ('Security', 'Security')], max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
